### PR TITLE
Migrate code into Tenantex.Repo

### PR DESCRIPTION
**Pull request by jbsmith**
Moved the list_tenants method into Tenantex.Repo
Made some small changes to simplify things

### CODE REVIEW

**Comment by jeffdeville** [comment]
Thanks JB!  I'll take a look asap!  It'll be nice to get this to a point where I feel comfortable pushing it to hex.  Side question. I've submitted a lot of patches to other repos, but have never been on the receiving end when the other individual doesn't have access to the repo.  (I'd give it to you, but promptworks is my employer).  Is there any better way to jointly contribute aside from the way we're just pasting code in markdown comments?  All I can think of would be a fork to a personal repo, and we'd share that repo.  Just a thought. Not a reflection on this PR's code at all (I haven't looked yet)

**Comment by jeffdeville** [comment]
Fixed the busted specs.  Here it is in patch format.

```
From 1df6c9b04813e5aac6a695cb7a90e8e1352dc641 Mon Sep 17 00:00:00 2001
From: Jeff Deville <jeffdeville@gmail.com>
Date: Fri, 19 May 2017 09:17:25 -0400
Subject: [PATCH] Fix specs

---
 lib/mix/tasks/tenantex.migrate.ex            | 5 +----
 lib/tenantex/prefix.ex                       | 4 +++-
 lib/tenantex/repo.ex                         | 8 ++------
 test/lib/mix/tasks/tenantex.migrate_test.exs | 3 ++-
 4 files changed, 8 insertions(+), 12 deletions(-)

diff --git a/lib/mix/tasks/tenantex.migrate.ex b/lib/mix/tasks/tenantex.migrate.ex
index a369cf2..591cbf0 100644
--- a/lib/mix/tasks/tenantex.migrate.ex
+++ b/lib/mix/tasks/tenantex.migrate.ex
@@ -2,13 +2,11 @@ defmodule Mix.Tasks.Tenantex.Migrate do
   use Mix.Task
   import Mix.Tenantex
   import Tenantex.Prefix
-  @shortdoc "Migrates every tenant defined in your load_tenants config"
+  @shortdoc "Migrates every tenant defined in your database"
 
   @moduledoc """
   Migrates all of the tenants
 
-  Notes: You must have the 'tenants' config option set.
-
   Any arguments you specify will be passed along directly to Ecto's migrate command,
   so they're all fair game as well.  That said, prefix (--prefix) and repo (-r/--repo)
   will be overridden by what is in your config.
@@ -27,7 +25,6 @@ defmodule Mix.Tasks.Tenantex.Migrate do
 
     Mix.Task.run "loadpaths", []
     Tenantex.list_tenants
-    |> Enum.map(&schema_name(&1))
     |> Enum.each(&migrator.(args, &1))
   end
 
diff --git a/lib/tenantex/prefix.ex b/lib/tenantex/prefix.ex
index 4d6f085..068a2ec 100644
--- a/lib/tenantex/prefix.ex
+++ b/lib/tenantex/prefix.ex
@@ -1,7 +1,9 @@
 defmodule Tenantex.Prefix do
   def strip_prefix(table_prefix), do: String.replace_prefix(table_prefix, get_prefix(), "")
   def schema_name(tenant) when is_integer(tenant), do: get_prefix() <> Integer.to_string(tenant)
-  def schema_name(tenant) when is_binary(tenant), do: get_prefix() <> tenant
+  def schema_name(tenant) when is_binary(tenant) do
+    if String.starts_with?(tenant, get_prefix()), do: tenant, else: get_prefix() <> tenant
+  end
 
   def schema_name(nil), do: raise ArgumentError, "Tenant can not be nil"
   def get_prefix() do
diff --git a/lib/tenantex/repo.ex b/lib/tenantex/repo.ex
index 0637fe9..a4e4324 100644
--- a/lib/tenantex/repo.ex
+++ b/lib/tenantex/repo.ex
@@ -234,17 +234,13 @@ defmodule Tenantex.Repo do
     |> Enum.filter(&(String.starts_with?(&1, get_prefix())))
   end
 
-  defp tenant_exists(tenant) do
-
-  end
-
   defp get_repo do
     case get_env(:tenantex, Tenantex)[:repo] do
       nil -> default_repo()
       repo -> repo
     end
   end
-  
+
   defp get_appname do
     Mix.Project.config()
     |> Keyword.fetch!(:app)
@@ -253,7 +249,7 @@ defmodule Tenantex.Repo do
   defp default_repo do
     get_appname()
     |> get_env(:ecto_repos)
-    |> List.first()    
+    |> List.first()
   end
 
 end
diff --git a/test/lib/mix/tasks/tenantex.migrate_test.exs b/test/lib/mix/tasks/tenantex.migrate_test.exs
index a6459dd..6569df1 100644
--- a/test/lib/mix/tasks/tenantex.migrate_test.exs
+++ b/test/lib/mix/tasks/tenantex.migrate_test.exs
@@ -3,7 +3,8 @@ defmodule Mix.Tasks.Tenantex.MigrateTest do
   import Mix.Tasks.Tenantex.Migrate, only: [run: 2]
 
   test "runs migration for each tenant, with the correct prefix" do
-    expected_args = ["-r", "REPO"]
+    :ok = Ecto.Adapters.SQL.Sandbox.checkout(Tenantex.TestTenantRepo)
+    expected_args = ["-r", "Tenantex.TestTenantRepo"]
     run(expected_args, fn(args, prefix) ->
       assert prefix in ~w(tenant_test1 tenant_test2)
       assert args == expected_args
-- 
2.12.0

```

**Comment by jeffdeville** [comment]
I think that if I'm going to push this to hex, there's a few things that probably need to happen first:

1. Review and update the docs
2. Generate the docs
3. Add Maria to the tests, instead of just postgres
4. Figure out how to get circleci to test against a range of dependencies for postgres/maria packages.

Agree/Disagree?  Did I forget anything?

**Comment by jeffdeville** [comment]
I guess I should get credo going as well.

**Comment by jeffdeville** [comment]
*2 More things:*

1. Looking at ecto's repo, they do:

     # Drivers
     {:db_connection, "~> 1.1", optional: true},
     {:postgrex, "~> 0.13.0", optional: true},
     {:mariaex, "~> 0.8.0", optional: true},

They're effectively locking the drivers down. I'm not sure I'm thrilled w/ that idea because I frankly don't want to have to stay on top of version bumps, or force people to put overrides in their mix.exs.

Since we are specifying an Ecto version under the covers anyway, I'd prefer to just rely on Ecto to provide the underlying db dependencies, and only have to track 1 thing.

2. I don't have support for rollback yet.  Because of the way I'm using it, I've been able to avoid absolutely needing it, but it is an unexpected oversight for users that I'd like to resolve.

**Comment by jbsmith** [comment]
The PR mechanism seems to work ok if we avoid pasting code into comment boxes

We can avoid using markdown (for code) if we create branches and use commits to structure our comments around, as I have started to do.
No need for me to have access directly, I am fine with keeping a local version that I can control

For others that might not be familiar, deps for this can be incorporated into your app’s mix.exs -> deps() like so

 {:tenantex, path: "./deps/tenantex"}
OR
 {:tenantex, git: "https://github.com/PERSONALREPO/tenantex.git", tag: "master"}

**Comment by jbsmith** [comment]
Just some thoughts regarding prep for Hex push

Docs need a handful of updates to reflect:
  

- the assumptions that have changed about where tenants are authoritatively listed
-   how the configs have changed, and what is now required vs optional (repo)
-   perhaps better describing what the config options achieve
-   describing the process of new tenant creation with associated migrations
-   describing how to conform queries to use the :prefix argument where necessary (with variations)
-   adding indications of how some of the helper methods we have added might be useful in workflows
-   further removal of apartmentex references to avoid confusion (re: hex package name etc) and perhaps additional pointers in the README to that project for reference and comparison or appreciation

**Pull request merged**
